### PR TITLE
Gamechat details

### PR DESCRIPTION
**Pull request by wowgr8**
## Description

This code will add the following to the game chat box:
- Vertical Scroll
- Border
- Fixed height
- Background color to sender's message
- Relocate input field above message thread
- Populate new messages above previous messages
- Set max character count to 50.

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|  ✓ | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

### Before

image

### After

image

### CODE REVIEW

**Comment by mautoranzo** [comment]
Is working perfectly! Just some suggestions that we can apply not just to this but all inputs in the game:
1) Enter key can send the message.  Enter=click on send
2)Set input to blank once the message is sent.

**Review by mautoranzo — APPROVED** [review]
Good job!

**Review by frankstepanski — APPROVED** [review]
Nice work, but eventually we need to get rid of those <br>'s.

**Comment by wowgr8** [comment]
> Nice work, but eventually we need to get rid of those 's.

Thanks Frank. I'm a bit lost, what `'s` are you referring to?

**Comment by frankstepanski** [comment]
@wowgr8 sorry, it took out my HTML tags. I said BRs lol

**Pull request merged**
