### PR TITLE
Playersinlobby

### PR DESCRIPTION
**Pull request by wowgr8**
## Description

Inside of the game lobby page, this code will display player usernames below the game room they are in.

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|  ✓ | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

### CODE REVIEW

**Comment by frankstepanski** [comment]
It seems that once you are in the room, it will display the users in the room, but as another user enters an existing room, it does not update other connected users view of the recently added user(s)

Screenshot 2023-04-16 at 9 29 45 PM

**Comment by mautoranzo** [comment]
The problem was in the back end. I think I fixed, please try again now.

**Review by frankstepanski — APPROVED** [review]
Looks good. We can handle the HTML and CSS later. 👍

**Review by mautoranzo — APPROVED** [review]
Working!

**Pull request merged**
